;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        dabbrev-expand
        forward-sexp
        indent-for-tab-command
        kill-region
        mc/copy
        mc/cut
        mc/paste
        my-comment-or-uncomment-region
        overwrite-mode
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        column-number-mode
        counsel-M-x
        counsel-find-file
        describe-variable
        end-of-buffer
        ivy-alt-done
        ivy-backward-delete-char
        ivy-forward-char
        ivy-switch-buffer
        line-number-mode
        mcs-alt-done
        mcs-cancel
        mcs-done
        mcs-done2
        mcs-mark-next-like-this
        mcs-minibuffer-keyboard-quit
        mcs-swiper
        minibuffer-keyboard-quit
        mode-line-previous-buffer
        mouse-drag-mode-line
        mouse-minor-mode-menu
        mouse-select-window
        mouse-set-region
        next-buff
        prev-buffer
        swiper
        swiper-mc
        perspsw1
        perspsw2
        perspsw3
        perspsw4
        perspsw5
        perspsw6
        perspsw7
        perspsw8
        perspsw9
        perspsw0
        next-error-no-select
        kill-buffer
        compile-goto-error
        ))
