;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        forward-sexp
        indent-for-tab-command
        kill-region
        mc/copy
        mc/cut
        mc/paste
        my-comment-or-uncomment-region
        overwrite-mode
        swiper
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        column-number-mode
        counsel-M-x
        counsel-find-file
        describe-variable
        end-of-buffer
        ivy-switch-buffer
        line-number-mode
        mode-line-previous-buffer
        mouse-drag-mode-line
        mouse-minor-mode-menu
        mouse-select-window
        mouse-set-region
        next-buff
        prev-buffer
        ))
